//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.239
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ClassLibrary1 {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Atteli {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Atteli() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ClassLibrary1.Atteli", typeof(Atteli).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        internal static System.Drawing.Bitmap aizmugure {
            get {
                object obj = ResourceManager.GetObject("aizmugure", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Ercens_Astoni {
            get {
                object obj = ResourceManager.GetObject("Ercens_Astoni", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Ercens_Cetri {
            get {
                object obj = ResourceManager.GetObject("Ercens_Cetri", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Ercens_Dama {
            get {
                object obj = ResourceManager.GetObject("Ercens_Dama", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Ercens_Desmit {
            get {
                object obj = ResourceManager.GetObject("Ercens_Desmit", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Ercens_Devini {
            get {
                object obj = ResourceManager.GetObject("Ercens_Devini", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Ercens_Divi {
            get {
                object obj = ResourceManager.GetObject("Ercens_Divi", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Ercens_Duzis {
            get {
                object obj = ResourceManager.GetObject("Ercens_Duzis", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Ercens_Kalps {
            get {
                object obj = ResourceManager.GetObject("Ercens_Kalps", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Ercens_Kungs {
            get {
                object obj = ResourceManager.GetObject("Ercens_Kungs", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Ercens_Pieci {
            get {
                object obj = ResourceManager.GetObject("Ercens_Pieci", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Ercens_Septini {
            get {
                object obj = ResourceManager.GetObject("Ercens_Septini", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Ercens_Sesi {
            get {
                object obj = ResourceManager.GetObject("Ercens_Sesi", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Ercens_Tris {
            get {
                object obj = ResourceManager.GetObject("Ercens_Tris", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Image1 {
            get {
                object obj = ResourceManager.GetObject("Image1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Karavs_Astoni {
            get {
                object obj = ResourceManager.GetObject("Karavs_Astoni", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Karavs_Cetri {
            get {
                object obj = ResourceManager.GetObject("Karavs_Cetri", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Karavs_Dama {
            get {
                object obj = ResourceManager.GetObject("Karavs_Dama", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Karavs_Desmit {
            get {
                object obj = ResourceManager.GetObject("Karavs_Desmit", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Karavs_Devini {
            get {
                object obj = ResourceManager.GetObject("Karavs_Devini", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Karavs_Divi {
            get {
                object obj = ResourceManager.GetObject("Karavs_Divi", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Karavs_Duzis {
            get {
                object obj = ResourceManager.GetObject("Karavs_Duzis", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Karavs_Kalps {
            get {
                object obj = ResourceManager.GetObject("Karavs_Kalps", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Karavs_Kungs {
            get {
                object obj = ResourceManager.GetObject("Karavs_Kungs", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Karavs_Pieci {
            get {
                object obj = ResourceManager.GetObject("Karavs_Pieci", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Karavs_Septini {
            get {
                object obj = ResourceManager.GetObject("Karavs_Septini", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Karavs_Sesi {
            get {
                object obj = ResourceManager.GetObject("Karavs_Sesi", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Karavs_Tris {
            get {
                object obj = ResourceManager.GetObject("Karavs_Tris", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Kreicis_Astoni {
            get {
                object obj = ResourceManager.GetObject("Kreicis_Astoni", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Kreicis_Cetri {
            get {
                object obj = ResourceManager.GetObject("Kreicis_Cetri", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Kreicis_Dama {
            get {
                object obj = ResourceManager.GetObject("Kreicis_Dama", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Kreicis_Desmit {
            get {
                object obj = ResourceManager.GetObject("Kreicis_Desmit", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Kreicis_Devini {
            get {
                object obj = ResourceManager.GetObject("Kreicis_Devini", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Kreicis_Divi {
            get {
                object obj = ResourceManager.GetObject("Kreicis_Divi", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Kreicis_Duzis {
            get {
                object obj = ResourceManager.GetObject("Kreicis_Duzis", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Kreicis_Kalps {
            get {
                object obj = ResourceManager.GetObject("Kreicis_Kalps", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Kreicis_Kungs {
            get {
                object obj = ResourceManager.GetObject("Kreicis_Kungs", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Kreicis_Pieci {
            get {
                object obj = ResourceManager.GetObject("Kreicis_Pieci", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Kreicis_Septini {
            get {
                object obj = ResourceManager.GetObject("Kreicis_Septini", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Kreicis_Sesi {
            get {
                object obj = ResourceManager.GetObject("Kreicis_Sesi", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Kreicis_Tris {
            get {
                object obj = ResourceManager.GetObject("Kreicis_Tris", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Pikis_Astoni {
            get {
                object obj = ResourceManager.GetObject("Pikis_Astoni", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Pikis_Cetri {
            get {
                object obj = ResourceManager.GetObject("Pikis_Cetri", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Pikis_Dama {
            get {
                object obj = ResourceManager.GetObject("Pikis_Dama", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Pikis_Desmit {
            get {
                object obj = ResourceManager.GetObject("Pikis_Desmit", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Pikis_Devini {
            get {
                object obj = ResourceManager.GetObject("Pikis_Devini", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Pikis_Divi {
            get {
                object obj = ResourceManager.GetObject("Pikis_Divi", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Pikis_Duzis {
            get {
                object obj = ResourceManager.GetObject("Pikis_Duzis", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Pikis_Kalps {
            get {
                object obj = ResourceManager.GetObject("Pikis_Kalps", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Pikis_Kungs {
            get {
                object obj = ResourceManager.GetObject("Pikis_Kungs", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Pikis_Pieci {
            get {
                object obj = ResourceManager.GetObject("Pikis_Pieci", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Pikis_Septini {
            get {
                object obj = ResourceManager.GetObject("Pikis_Septini", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Pikis_Sesi {
            get {
                object obj = ResourceManager.GetObject("Pikis_Sesi", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Pikis_Tris {
            get {
                object obj = ResourceManager.GetObject("Pikis_Tris", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
    }
}
